replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/mht1003/astro
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 4321

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

